#============

# Run these commands to build:
# APP_TAG_NG="v0.0.1-dev"
# USER_GITHUB="unit-cesar"
# APP_NAME_NG="com.guiafederal-front"
# docker build --file Dockerfile-dev --build-arg APP_NAME_NG=$APP_NAME_NG --build-arg APP_TAG_NG=$APP_TAG_NG --build-arg USER_GITHUB=$USER_GITHUB --tag i_${APP_NAME_NG}:${APP_TAG_NG} .

FROM node:18.12.1 as angularApp
WORKDIR /app
ARG APP_NAME_NG
ARG APP_TAG_NG
ARG USER_GITHUB
RUN echo "Cloning public repo from GitHub to WORKDIR (${USER_GITHUB}/${APP_NAME_NG}:${APP_TAG_NG})" >> ../docker-build-${APP_NAME_NG}:${APP_TAG_NG}.log
#RUN git clone https://github.com/${USER_GITHUB}/${APP_NAME_NG}.git --branch ${APP_TAG_NG} .
RUN git clone https://github.com/${USER_GITHUB}/${APP_NAME_NG}.git .
RUN npm install
RUN npm run build

# example of the network
# https://docs.docker.com/engine/reference/builder/#run---network
# RUN --network=none pip install --find-links wheels mypackage

FROM httpd:2.4 as apacheServer
ARG APP_NAME_NG
COPY --from=angularApp /app/dist/${APP_NAME_NG} /usr/local/apache2/htdocs/
EXPOSE 80

RUN echo "Done!!!"  >> ../docker-build-${APP_NAME_NG}:${APP_TAG_NG}.log

#===================
